/**
 * A mapping of HTTP status codes to descriptions.
 * Source: https://www.rfc-editor.org/rfc/rfc9110.html
 */
export const description = {
  CONTINUE: "Continue",
  100: "Continue",
  SWITCHING_PROTOCOLS: "Switching Protocols",
  101: "Switching Protocols",
  PROCESSING: "Processing",
  102: "Processing",
  EARLY_HINTS: "Early Hints",
  103: "Early Hints",
  OK: "OK",
  200: "OK",
  CREATED: "Created",
  201: "Created",
  ACCEPTED: "Accepted",
  202: "Accepted",
  NON_AUTHORITATIVE_INFORMATION: "Non-Authoritative Information",
  203: "Non-Authoritative Information",
  NO_CONTENT: "No Content",
  204: "No Content",
  RESET_CONTENT: "Reset Content",
  205: "Reset Content",
  PARTIAL_CONTENT: "Partial Content",
  206: "Partial Content",
  MULTI_STATUS: "Multi-Status",
  207: "Multi-Status",
  ALREADY_REPORTED: "Already Reported",
  208: "Already Reported",
  IM_USED: "IM Used",
  226: "IM Used",
  MULTIPLE_CHOICES: "Multiple Choices",
  300: "Multiple Choices",
  MOVED_PERMANENTLY: "Moved Permanently",
  301: "Moved Permanently",
  FOUND: "Found",
  302: "Found",
  SEE_OTHER: "See Other",
  303: "See Other",
  NOT_MODIFIED: "Not Modified",
  304: "Not Modified",
  USE_PROXY: "Use Proxy",
  305: "Use Proxy",
  TEMPORARY_REDIRECT: "Temporary Redirect",
  307: "Temporary Redirect",
  PERMANENT_REDIRECT: "Permanent Redirect",
  308: "Permanent Redirect",
  BAD_REQUEST: "Bad Request",
  400: "Bad Request",
  UNAUTHORIZED: "Unauthorized",
  401: "Unauthorized",
  PAYMENT_REQUIRED: "Payment Required",
  402: "Payment Required",
  FORBIDDEN: "Forbidden",
  403: "Forbidden",
  NOT_FOUND: "Not Found",
  404: "Not Found",
  METHOD_NOT_ALLOWED: "Method Not Allowed",
  405: "Method Not Allowed",
  NOT_ACCEPTABLE: "Not Acceptable",
  406: "Not Acceptable",
  PROXY_AUTHENTICATION_REQUIRED: "Proxy Authentication Required",
  407: "Proxy Authentication Required",
  REQUEST_TIMEOUT: "Request Timeout",
  408: "Request Timeout",
  CONFLICT: "Conflict",
  409: "Conflict",
  GONE: "Gone",
  410: "Gone",
  LENGTH_REQUIRED: "Length Required",
  411: "Length Required",
  PRECONDITION_FAILED: "Precondition Failed",
  412: "Precondition Failed",
  CONTENT_TOO_LARGE: "Content Too Large",
  413: "Content Too Large",
  URI_TOO_LONG: "URI Too Long",
  414: "URI Too Long",
  UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type",
  415: "Unsupported Media Type",
  RANGE_NOT_SATISFIABLE: "Range Not Satisfiable",
  416: "Range Not Satisfiable",
  EXPECTATION_FAILED: "Expectation Failed",
  417: "Expectation Failed",
  MISDIRECTED_REQUEST: "Misdirected Request",
  421: "Misdirected Request",
  UNPROCESSABLE_CONTENT: "Unprocessable Content",
  422: "Unprocessable Content",
  LOCKED: "Locked",
  423: "Locked",
  FAILED_DEPENDENCY: "Failed Dependency",
  424: "Failed Dependency",
  TOO_EARLY: "Too Early",
  425: "Too Early",
  UPGRADE_REQUIRED: "Upgrade Required",
  426: "Upgrade Required",
  PRECONDITION_REQUIRED: "Precondition Required",
  428: "Precondition Required",
  TOO_MANY_REQUESTS: "Too Many Requests",
  429: "Too Many Requests",
  REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
  431: "Request Header Fields Too Large",
  UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable For Legal Reasons",
  451: "Unavailable For Legal Reasons",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  500: "Internal Server Error",
  NOT_IMPLEMENTED: "Not Implemented",
  501: "Not Implemented",
  BAD_GATEWAY: "Bad Gateway",
  502: "Bad Gateway",
  SERVICE_UNAVAILABLE: "Service Unavailable",
  503: "Service Unavailable",
  GATEWAY_TIMEOUT: "Gateway Timeout",
  504: "Gateway Timeout",
  HTTP_VERSION_NOT_SUPPORTED: "HTTP Version Not Supported",
  505: "HTTP Version Not Supported",
  VARIANT_ALSO_NEGOTIATES: "Variant Also Negotiates",
  506: "Variant Also Negotiates",
  INSUFFICIENT_STORAGE: "Insufficient Storage",
  507: "Insufficient Storage",
  LOOP_DETECTED: "Loop Detected",
  508: "Loop Detected",
  NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
  511: "Network Authentication Required",
} as const;

/**
 * A mapping of HTTP status descriptions (snake-case, upper-cased) to codes.
 * Source: https://www.rfc-editor.org/rfc/rfc9110.html
 */
export const code = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  CONTENT_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_CONTENT: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;
